/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;


import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LISHA
 */
public final class billPage extends javax.swing.JFrame {

    /**
     * Creates new form billPage
     */
    
    DefaultTableModel billPageModel;
    Connection conn=null;
    ResultSet rs=null;
    Statement st=null;
    PreparedStatement pst=null;
    
    public void tableReaders()
    {
        billPageModel=(DefaultTableModel) pro_table.getModel();
        Object[] tableReaders=new Object[]{"PRO_ID","NAME","PRICE","QUANTITY","TOTAL"};
        billPageModel.setColumnIdentifiers(tableReaders);
       
    }
    public billPage() {
        initComponents();
        tableReaders();
    }
    public billPage(String c, String c1,String c2, String c3) {
        initComponents();
        cid.setText(c);
        Random rand=new Random();
        int temp=rand.nextInt(9000000)+1000000;
        billno.setText("B"+Integer.toString(temp));
        cusid.setText(c1);
        cusname.setText(c2);
        cusmob.setText(c3);
        //total.setText(t);
        //tableReaders();
        Calendar c5=new GregorianCalendar();
         int sec=c5.get(Calendar.SECOND);
         int min=c5.get(Calendar.MINUTE);
         int hr=c5.get(Calendar.HOUR);
         time.setText(hr+":"+min+":"+sec);
    }
    
   public billPage(String c, String c1,String c2, String c3,String t) {
        initComponents();
        cid.setText(c);
        Random rand=new Random();
        int temp=rand.nextInt(9000000)+1000000;
        billno.setText("B"+Integer.toString(temp));
        cusid.setText(c1);
        cusname.setText(c2);
        cusmob.setText(c3);
        total.setText(t);
        Calendar c5=new GregorianCalendar();
         int sec=c5.get(Calendar.SECOND);
         int min=c5.get(Calendar.MINUTE);
         int hr=c5.get(Calendar.HOUR);
         time.setText(hr+":"+min+":"+sec);
        tableReaders();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        billno = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pro_table = new javax.swing.JTable();
        cusname = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        cusid = new javax.swing.JTextField();
        cusmob = new javax.swing.JTextField();
        billdate = new com.toedter.calendar.JDateChooser();
        total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setText("BILL NO :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 20, 60, 20);

        jLabel4.setText("DATE:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 50, 40, 30);

        jLabel6.setText("CASHIER ID:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 100, 80, 20);

        jLabel8.setText("CUSTOMER ID:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 134, 100, 20);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel10.setText("BILL");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(390, 20, 100, 40);

        jLabel11.setText("NAME :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(295, 134, 40, 20);

        jLabel13.setText("STORE ID :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(634, 10, 70, 30);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("STRMANG01");
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(710, 10, 80, 30);

        jLabel15.setText("CONTACT:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(630, 50, 90, 30);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("9854126570");
        jLabel16.setOpaque(true);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(710, 50, 80, 30);

        jLabel17.setText("MOBILE :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(590, 134, 60, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 520, 80, 40);

        jLabel19.setText("AMOUNT :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(460, 520, 60, 30);

        billno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billnoActionPerformed(evt);
            }
        });
        jPanel1.add(billno);
        billno.setBounds(110, 10, 140, 30);
        jPanel1.add(cid);
        cid.setBounds(110, 90, 120, 30);

        pro_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(pro_table);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(140, 190, 560, 310);
        jPanel1.add(cusname);
        cusname.setBounds(340, 130, 160, 30);

        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel1.add(time);
        time.setBounds(690, 90, 110, 30);
        jPanel1.add(cusid);
        cusid.setBounds(110, 130, 120, 30);
        jPanel1.add(cusmob);
        cusmob.setBounds(650, 130, 120, 30);
        jPanel1.add(billdate);
        billdate.setBounds(110, 50, 140, 30);
        jPanel1.add(total);
        total.setBounds(519, 520, 70, 30);

        jLabel3.setText("Time:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(640, 90, 40, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("Thank you for shopping. Visit again");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(324, 570, 230, 15);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 840, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
        Date date=new Date(billdate.getDate().getTime());
       
        int a=Integer.parseInt(total.getText());
        Class.forName("oracle.jdbc.driver.OracleDriver");
        conn=java.sql.DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","chen","Dsouzacompound1");
        PreparedStatement ps=conn.prepareStatement("insert into bill(billno,billcost,billdate,cusid,cashierid) VALUES(?,?,?,?,?)");
        ps.setString(1, billno.getText());
        ps.setInt(2, a);
        ps.setDate(3, date);
        ps.setString(4, cusid.getText());
        ps.setString(5, cid.getText());
        ps.execute();
        JOptionPane.showMessageDialog(null, "PROCEED FOR PRINTING");
        conn.close();
           
        print();
        
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(billPage.class.getName()).log(Level.SEVERE, null, ex);
         JOptionPane.showMessageDialog(null, ex);
    }
         
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void billnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billnoActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser billdate;
    private javax.swing.JTextField billno;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cusid;
    private javax.swing.JTextField cusmob;
    private javax.swing.JTextField cusname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable pro_table;
    private javax.swing.JTextField time;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

private void print()
{
    PrinterJob job = PrinterJob.getPrinterJob();
    job.setJobName("Print Data");
    job.setPrintable(new Printable(){
    public int print(Graphics pg,PageFormat pf, int pageNum){
    pf.setOrientation(PageFormat.LANDSCAPE);
    if(pageNum>0){
                    return Printable.NO_SUCH_PAGE;
    }
    Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.75,0.75);
                jPanel1.paint(g2);  
    return Printable.PAGE_EXISTS;     
    }
    });
    boolean ok = job.printDialog();
    if(ok){
    try{    
        job.print();
    }
    catch (PrinterException ex){}
    }        
}

}
