/* * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

/**
 *
 * @author LISHA
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public final class product_page extends javax.swing.JFrame {
    float sum=0;
    int row=0;
    DefaultTableModel dm;
    TableRowSorter<DefaultTableModel> sorter = null;
    String c,c1,c2,c3,t;
    //ViewSelectedRowJFrame view=new ViewSelectedRowJFrame[];
   // billPage bp=new billPage(c,c1,c2,c3,t);
    
    public void addTableHeader() {
        dm = (DefaultTableModel) pro_table.getModel();
        Object[] newIdentifiers = new Object[]{"PRO_ID", "NAME", "PRICE", "QUANTITY", "TOTAL_PRICE"};
        dm.setColumnIdentifiers(newIdentifiers);
        //Get Image column and override  TableCellRenderer class component method (getTableCellRendererComponent)
        //jTable1.getColumn("Image").setCellRenderer(new myTableCellRenderer());
    
    }
    public product_page() {
        initComponents();
        addTableHeader();
    }
    public product_page(String s, String s1, String s2,String s3) {
        initComponents();
        addTableHeader();
        cid.setText(s);
        cusid.setText(s1);
        cusname.setText(s2);
        cusmob.setText(s3);
        
    }
    Connection conn=null;
    ResultSet rs=null;
    Statement st=null;
    PreparedStatement pst=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pro_id = new javax.swing.JComboBox<>();
        quan1 = new javax.swing.JSpinner();
        cusname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cid = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        pro_table = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        cusid = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        cusmob = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("CUSTOMER NAME :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 90, 150, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("CUSTOMER ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 48, 130, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("MOBILE NO :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 120, 110, 40);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("PRODUCT DETAILS");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(340, 10, 220, 40);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setText("CASHIER ID :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(930, 20, 110, 18);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setText("PRODUCT ID :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(450, 60, 110, 20);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setText("QUANTITY :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(460, 118, 100, 30);

        pro_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pro_idMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pro_idMousePressed(evt);
            }
        });
        jPanel1.add(pro_id);
        pro_id.setBounds(570, 50, 100, 40);
        jPanel1.add(quan1);
        quan1.setBounds(570, 120, 80, 30);
        jPanel1.add(cusname);
        cusname.setBounds(180, 90, 150, 30);

        cid.setContentType(""); // NOI18N
        jScrollPane1.setViewportView(cid);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(1030, 12, 100, 30);

        pro_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(pro_table);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(180, 180, 680, 402);

        jScrollPane3.setViewportView(cusid);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(180, 50, 150, 30);

        jScrollPane5.setViewportView(cusmob);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(180, 130, 150, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("AMOUNT :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(510, 610, 70, 30);

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(740, 610, 80, 23);

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total);
        total.setBounds(580, 610, 100, 30);

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButton2.setText("ADD PRODUCTS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(710, 120, 140, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LISHA\\Desktop\\lincia\\Supermarket\\supermarketcart.JPG")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1220, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
        //demo1();
        Class.forName("oracle.jdbc.driver.OracleDriver");
        conn=java.sql.DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","username","password");
        String s=pro_id.getSelectedItem().toString();
        st=conn.createStatement();
        rs= st.executeQuery("select proid,proname,proprice,proquantity from product where proid='"+s+"'");
        rs.next();
        String s1=rs.getString(1);
        String s2=rs.getString(2);
        int i1=rs.getInt(3);
        int qu=rs.getInt(4);
       
        int i2=(int) quan1.getValue();
        if(i2>0){
        int col=0;
        pro_table.setValueAt(s1, row, col);
        col++;
        pro_table.setValueAt(s2, row, col);
        col++;
        pro_table.setValueAt(i1, row, col);
        col++;
        pro_table.setValueAt(quan1.getValue(), row, col);
        col++;
        int t=i1*i2;
        sum=sum+t;
        pro_table.setValueAt(t, row, col);
        row++;
        String E=Integer.toString((int) sum);
        
        total.setText(E);
        int finalquan=qu-i2;
        if(finalquan<2){
             JOptionPane.showMessageDialog(null, "Stock of this product is less");
        }
        PreparedStatement ps=conn.prepareStatement("update product set proquantity='"+finalquan+"'where proid='"+s1+"'");
        ps.executeUpdate();
        st.close();
        ps.close();
        conn.close();   
        }
        else{
            JOptionPane.showMessageDialog(null, "SET QUANTITY GREATER THAN 0");
        }
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(billPage.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pro_idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pro_idMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pro_idMousePressed

    private void pro_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pro_idMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            pro_id.removeAllItems();
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn=java.sql.DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","chen","Dsouzacompound1");
            st=conn.createStatement();
            rs=st.executeQuery("select proid from product");
          
            while(rs.next()){
                pro_id.addItem(rs.getString(1));
        }
         conn.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(product_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_pro_idMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        c=cid.getText();
        c1=cusid.getText();
        c2=cusname.getText();
        c3=cusmob.getText();
        t=total.getText();
        billPage bp = new billPage(c,c1,c2,c3,t);
        int[] getSelectedRows;
        getSelectedRows = pro_table.getSelectedRows();
        Object[] newRows=new Object[5];        
        for(int i=0;i<getSelectedRows.length ;i++)
        {
            newRows[0]=dm.getValueAt(getSelectedRows[i], 0);
            newRows[1]=dm.getValueAt(getSelectedRows[i], 1);
            newRows[2]=dm.getValueAt(getSelectedRows[i], 2);
            newRows[3]=dm.getValueAt(getSelectedRows[i], 3);
            newRows[4]=dm.getValueAt(getSelectedRows[i], 4);
            bp.billPageModel.addRow(newRows);    
        }
        
        bp.setVisible(true);
         dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane cid;
    private javax.swing.JTextPane cusid;
    private javax.swing.JTextPane cusmob;
    private javax.swing.JTextField cusname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox<String> pro_id;
    private javax.swing.JTable pro_table;
    private javax.swing.JSpinner quan1;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
