/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LISHA
 */
public class updating_customer extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs=null;
    Statement st=null;
    PreparedStatement pst=null;
    /**
     * Creates new form updating_customer
     */
    public updating_customer() {
        initComponents();
    }
     public updating_customer(String s,String s1,String s2,String s3) {
        initComponents();
        cid.setText(s);
        cus_id.setText(s1);
        cus_name.setText(s2);
        cus_mob.setText(s3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cus_id = new javax.swing.JTextField();
        cus_name = new javax.swing.JTextField();
        cus_mob = new javax.swing.JTextField();
        cus_new = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("UPDATE CUSTOMER DETAILS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 110, 370, 60);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("CUSTOMER ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(204, 230, 120, 18);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("NAME :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(260, 270, 60, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("MOBILE :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 330, 70, 18);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("NEW MOBILE:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 380, 110, 18);

        cus_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_idActionPerformed(evt);
            }
        });
        jPanel1.add(cus_id);
        cus_id.setBounds(340, 220, 160, 40);

        cus_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_nameActionPerformed(evt);
            }
        });
        jPanel1.add(cus_name);
        cus_name.setBounds(340, 270, 160, 40);
        jPanel1.add(cus_mob);
        cus_mob.setBounds(340, 320, 160, 40);

        cus_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_newActionPerformed(evt);
            }
        });
        jPanel1.add(cus_new);
        cus_new.setBounds(340, 370, 160, 40);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setText("CASHIER ID:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(820, 100, 93, 18);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(353, 473, 130, 30);
        jPanel1.add(cid);
        cid.setBounds(940, 90, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LISHA\\Desktop\\lincia\\Supermarket\\supermarketcart.JPG")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1090, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cus_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cus_nameActionPerformed

    private void cus_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cus_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        // TODO add your handling code here:
        Class.forName("oracle.jdbc.driver.OracleDriver");
        conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","username","password");
        String s=cus_new.getText();
        String s1=cus_id.getText();
        
        pst=conn.prepareStatement("update Customer set cusmob='"+s+"'Where cusid='"+s1+"'");
        pst.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "MOBILE NUMBER UPDATED");
        //display1();
        String s2=cus_name.getText();
        new product_page(cid.getText(),s1,s2,s).setVisible(true);
        conn.close();
        
        
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(search_customer.class.getName()).log(Level.SEVERE, null, ex);
         JOptionPane.showMessageDialog(null, ex);
    }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cus_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cus_newActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updating_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updating_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updating_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updating_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updating_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cus_id;
    private javax.swing.JTextField cus_mob;
    private javax.swing.JTextField cus_name;
    private javax.swing.JTextField cus_new;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
